### PR TITLE
Removed tests that use network connection.

### PR DESCRIPTION
**Pull request by iCHAIT**
## Changes in this PR.

- [X] Removed `test_create_or_update_create_time_catch_request_error`
- [X] Removed `test_create_or_update_create_user_catch_request_error`

@osuosl/devs

### CODE REVIEW

**Comment by matthewrsj** [comment]
+1

**Comment by matthewrsj** [comment]
@iCHAIT rebase needed

**Comment by iCHAIT** [comment]
@matthewrsj Done.

**Comment by matthewrsj** [comment]
+1

**Pull request merged**
