### PR TITLE
Fix optional params for users

### LINKED ISSUE #116: Users optional fields are incorrect
prepend site- to perm fields
displayname => display_name

### PR DESCRIPTION
**Pull request by matthewrsj**
Fixes #116 

- Fixes bug where optional user params were incorrect, causing `create_user` and `update_user` methods to fail with timesync errors.
- Fixes bug where get_* methods were returning doubly-nested lists

### CODE REVIEW

**Comment by Kennric** [comment]
+1

**Comment by matthewrsj** [comment]
latest commit fixes from this:

```
>>> ts.get_users()
[{u'username': u'admin', u'display_name': u'root', u'created_at': u'2016-03-22', u'site_admin': True, u'updated_at': None, u'site_manager': True, u'meta': u'Root user. Created by setup script. Use to create other users.', u'site_spectator': True, u'active': True, u'deleted_at': None, u'email': None}, {u'username': u'patcht', u'display_name': u'Tristan Patch', u'created_at': u'2016-03-22', u'site_admin': True, u'updated_at': u'2016-03-22', u'site_manager': True, u'meta': None, u'site_spectator': True, u'active': True, u'deleted_at': None, u'email': u'patcht@osuosl.org'}]
>>> ts.get_times()
[[]]
>>> ts.get_activities()
[[{u'uuid': u'2a1477ad-74e8-4d6a-a8fe-de07ea2d05a3', u'created_at': u'2016-03-22', u'updated_at': None, u'name': u'Development', u'deleted_at': None, u'slug': u'dev', u'revision': 1}, {u'uuid': u'aea9825d-ded6-444d-be7e-6757ce621807', u'created_at': u'2016-03-22', u'updated_at': None, u'name': u'Documentation', u'deleted_at': None, u'slug': u'docs', u'revision': 1}]]
>>> ts.get_projects()
[[{u'uuid': u'2066a38e-ad7d-4bce-9f73-67ad9370882f', u'updated_at': None, u'default_activity': None, u'created_at': u'2016-03-22', u'uri': u'https://github.com/osuosl/timesync', u'name': u'TimeSync API', u'users': {u'patcht': {u'member': True, u'manager': True, u'spectator': True}}, u'deleted_at': None, u'slugs': [u'timesync', u'ts'], u'revision': 1}, {u'uuid': u'9aba2c72-6476-4a1f-9242-600ca5ca02a3', u'updated_at': None, u'default_activity': None, u'created_at': u'2016-03-22', u'uri': u'https://github.com/osuosl/timesync-node', u'name': u'TimeSync Node', u'users': {u'patcht': {u'member': True, u'manager': True, u'spectator': True}}, u'deleted_at': None, u'slugs': [u'timesync-node', u'tsn'], u'revision': 1}]]
>>> 
```

to this:

```
>>> ts.get_users()
[{u'username': u'admin', u'display_name': u'root', u'created_at': u'2016-03-22', u'site_admin': True, u'updated_at': None, u'site_manager': True, u'meta': u'Root user. Created by setup script. Use to create other users.', u'site_spectator': True, u'active': True, u'deleted_at': None, u'email': None}, {u'username': u'patcht', u'display_name': u'Tristan Patch', u'created_at': u'2016-03-22', u'site_admin': True, u'updated_at': u'2016-03-22', u'site_manager': True, u'meta': None, u'site_spectator': True, u'active': True, u'deleted_at': None, u'email': u'patcht@osuosl.org'}]
>>> ts.get_times()
[]
>>> ts.get_projects()
[{u'uuid': u'2066a38e-ad7d-4bce-9f73-67ad9370882f', u'updated_at': None, u'default_activity': None, u'created_at': u'2016-03-22', u'uri': u'https://github.com/osuosl/timesync', u'name': u'TimeSync API', u'users': {u'patcht': {u'member': True, u'manager': True, u'spectator': True}}, u'deleted_at': None, u'slugs': [u'timesync', u'ts'], u'revision': 1}, {u'uuid': u'9aba2c72-6476-4a1f-9242-600ca5ca02a3', u'updated_at': None, u'default_activity': None, u'created_at': u'2016-03-22', u'uri': u'https://github.com/osuosl/timesync-node', u'name': u'TimeSync Node', u'users': {u'patcht': {u'member': True, u'manager': True, u'spectator': True}}, u'deleted_at': None, u'slugs': [u'timesync-node', u'tsn'], u'revision': 1}]
>>> ts.get_activities()
[{u'uuid': u'2a1477ad-74e8-4d6a-a8fe-de07ea2d05a3', u'created_at': u'2016-03-22', u'updated_at': None, u'name': u'Development', u'deleted_at': None, u'slug': u'dev', u'revision': 1}, {u'uuid': u'aea9825d-ded6-444d-be7e-6757ce621807', u'created_at': u'2016-03-22', u'updated_at': None, u'name': u'Documentation', u'deleted_at': None, u'slug': u'docs', u'revision': 1}]
>>> 
```

**Comment by LyonesGamer** [comment]
Looks good to me. +1

**Comment by Kennric** [comment]
I think that's got it. +1

**Pull request merged**
