### PR TITLE
Removed owner field from project requirements, fixed tests to match

### PR DESCRIPTION
**Pull request by MaraJade**

### CODE REVIEW

**Comment by Kennric** [comment]
Tests and code change looks fine, but please remove the dist egg-info files - those are all generated when the package is created, and shouldn't be in the repo

**Comment by LyonesGamer** [comment]
I'd add them to the .gitignore, and add that to the PR so it doesn't become a problem again.

**Comment by matthewrsj** [comment]
Shouldn't owner be replaced by manager, not removed?

**Comment by matthewrsj** [comment]
Or is manager optional and should therefore be added to the optional list?

**Comment by Kennric** [comment]
I believe the creator will be added to the manager role by Timesync itself, but there isn't currently a mechanism to specify user roles on project creation/update.

**Comment by Kennric** [comment]
Looks ok to me. +1

**Comment by matthewrsj** [comment]
+1 after discussion in IRC about sticking to **current** API specification.

**Pull request merged**
