### PR TITLE
Added "user" query parameter to get_projects

### PR DESCRIPTION
**Pull request by aaroncohen73**
fixes issue #163 

## Changes in this PR.

- [X] Added support for the "user" query parameter on the `/projects` TimeSync endpoint
- [X] Added documentation for the new parameter

## Testing this PR.

1. Run `make verify`
2. Run this script with `python`:

```
import pymesync
ts = pymesync.TimeSync(baseurl='http://timesync-staging.osuosl.org/v0')
ts.authenticate('admin', 'timesync-staging', 'password')
ts.get_projects({"user": ["mrsj"]})
```

See that all of the projects that were returned contain the user "mrsj"

@osuosl/devs

### CODE REVIEW

**Comment by subnomo** [comment]
Looks good. :+1:

**Comment by ElijahCaine** [comment]
@aaroncohen73 When I run that *exact* script (with the addition of printing the last two lines) I get this output:
```python
{u'status': 401, u'text': {}, u'error': u'Authentication failure'}
[{'pymesync error': 'Not authenticated with TimeSync, call self.authenticate() first'}]
```

**Comment by aaroncohen73** [comment]
@ElijahCaine It looks like it's not working because the staging server is broken at the moment

**Comment by Kennric** [comment]
Looks good. +1

**Pull request merged**
