### PR TITLE
Fixed Unicode support for create/update user

### PR DESCRIPTION
**Pull request by aaroncohen73**
fixes issue #149 

## Changes in this PR.

- [X] If "password" is a Unicode object inside create/update user, encode it as UTF-8 so bcrypt doesn't raise a TypeError

## Testing this PR.

1. Run `make test`
2. Attempt to create/update a user with a Unicode password while authenticated as a site admin

@osuosl/devs

### CODE REVIEW

**Comment by matthewrsj** [comment]
Thank you for fixing the bug. Please add a test or two to test the change.

**Comment by aaroncohen73** [comment]
@matthewrsj Tests have been added

**Comment by matthewrsj** [comment]
Awesome, thanks @aaroncohen73. You will get my +1 once you rebase.

**Comment by ElijahCaine** [comment]
Tests pass and code looks good.

Small amount of feedback. Once that's addressed +1

**Comment by aaroncohen73** [comment]
@matthewrsj @ElijahCaine

**Comment by ElijahCaine** [comment]
Thanks for that slight reactor. Still got a +1 from me.

**Comment by matthewrsj** [comment]
gah. you had old commits after that rebase...

**Pull request merged**
