### PR TITLE
Python 3 Support

### PR DESCRIPTION
**Pull request by aaroncohen73**
fixes issue #141 

## Changes in this PR.

- [X] Compatibility between Python 2 and Python 3 has been added
- [X] Makefile moved to repository root and tests moved to their own directory (See [here](https://mail.python.org/pipermail/python-3000/2007-April/006793.html) for why)
- [X] `tests.py` has been moved to `test_pymesync.py` for more consistent naming
- [X] Tests now run with `nosetests` instead of running them as scripts directly
- [X] Patching mock functions for the `requests` module inside `test_pymesync.py` has been improved

## Testing this PR.

1. In a Python 2 virtualenv, run `make verify` and see that no errors come up.
2. Create a Python 3 virtualenv with the command `mkvirtualenv -p /usr/bin/python3 venv3`.
3. Inside the Python 3 virtualenv, run `make verify` and see that no errors come up.

@osuosl/devs

### CODE REVIEW

**Comment by ElijahCaine** [comment]
@aaroncohen73 I get build failures in the python3 virtualenv when running `pip install -r requirements.txt` for `bcrypt` and `cffi`. `cffi` isn't explicitly listed in our requirements but is a dependency. The exact errors are:
```
    c/_cffi_backend.c:2:20: fatal error: Python.h: No such file or directory
```
for the `cffi` error and the `bcrypt` error output is *very* long. Here's a pastebin of the entire output: https://pastebin.osuosl.org/39651/

**Comment by aaroncohen73** [comment]
@ElijahCaine The package python3-dev needs to installed in order for modules with a C component such as bcrypt to use the python 3 headers.

**Comment by ElijahCaine** [comment]
So status:
A. This has some conflicts that need to be resolved after some recent merges.
B. Our workstations don't currently have the python3-dev package installed. I'm going to make a change to our infra to get it installed and hopefully this will work then.

**Comment by jphilipsen05** [comment]
If this could be submitted in development that would be great. I am trying to run this in python3 and it looks like there are some major updates here including in the docs. I was looking at making some changes, but they are already in this pull request.

**Comment by aaroncohen73** [comment]
@jphilipsen05 Our process for merging PRs is that they have to be reviewed and approved by two other OSL members. Since most of the other Pymesync developers have been out of office this week, this probably won't get merged into the develop branch until next week at the earliest. However, since this is a significant feature addition it's likely that the review will take longer and small nitpicky changes will have to be made.

If you want to help out in the meantime, there's a [PR open](https://github.com/osuosl/climesync/pull/42) for Climesync (A Pymesync CLI frontend) that needs feedback and testing.

**Comment by subnomo** [comment]
Looks good. :+1:

**Comment by subnomo** [comment]
@aaroncohen73 I'd like to have pymesync support Python 3, rebase this and we'll see if we can get it merged.

**Comment by Kennric** [comment]
Looks good to me. +1

**Comment by ElijahCaine** [comment]
```
$ virtualenv -p /usr/bin/python2 venv2 && virtualenv -p /usr/bin/python3 venv3 \
&& source venv2/bin/activate && pip install -Ur requirements.txt && make verify && deactivate \
&& source venv3/bin/activate && pip install -Ur requrements.txt && make verify && deactivate
[ ... ]
Ran 169 tests in 1.982s
[ ... ]
Ran 169 tests in 1.492s
```
Everything looks good to me here.  :+1:

**Pull request merged**
